export class PAGE_PATH {
  static readonly MAIN_PAGE: string = "main_page"
  static readonly MAIN_PAGE_ID: string = "mainNavigation"
  static readonly SEARCH_PAGE: string = "SearchView"
  static readonly SEARCH_RESULT_PAGE: string = "SearchResultView"
  static readonly LOGIN_PAGE: string = "LoginView" // 搜索结构页面
  static readonly SETTING_PAGE: string = "SettingView" // 设置页面
  static readonly AI_CUSTOMER_PAGE: string = "AICustomerView" // 搜索结构页面
  static readonly GOODS_PAGE: string = "GoodsView" // 商品详情页面
  static readonly CART_PAGE: string = "CartView" // 购物车页面
  static readonly CHECK_PAGE: string = "CheckView" // 核对订单页面
  static readonly PAY_PAGE: string = "PayView" // 支付页面
}